export enum ActivityType {
  TASK = "TASK",
  PROJECT = "PROJECT",
  DOCUMENT = "DOCUMENT",
  USER = "USER",
  SURVEY = "SURVEY",
  COMMENT = "COMMENT",
  CHAT = "CHAT",
  NOTIFICATION = "NOTIFICATION",
  SYSTEM = "SYSTEM",
}

export enum ActivityAction {
  TASK_CREATED = "TASK_CREATED",
  TASK_UPDATED = "TASK_UPDATED",
  TASK_DELETED = "TASK_DELETED",
  TASK_ASSIGNED = "TASK_ASSIGNED",
  TASK_UNASSIGNED = "TASK_UNASSIGNED",
  TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED",
  TASK_PRIORITY_CHANGED = "TASK_PRIORITY_CHANGED",
  TASK_DUE_DATE_CHANGED = "TASK_DUE_DATE_CHANGED",
  TASK_COMMENTED = "TASK_COMMENTED",

  PROJECT_CREATED = "PROJECT_CREATED",
  PROJECT_UPDATED = "PROJECT_UPDATED",
  PROJECT_DELETED = "PROJECT_DELETED",
  PROJECT_STARTED = "PROJECT_STARTED",
  PROJECT_COMPLETED = "PROJECT_COMPLETED",
  PROJECT_PAUSED = "PROJECT_PAUSED",
  PROJECT_ARCHIVED = "PROJECT_ARCHIVED",
  PROJECT_MEMBER_ADDED = "PROJECT_MEMBER_ADDED",
  PROJECT_MEMBER_REMOVED = "PROJECT_MEMBER_REMOVED",
  PROJECT_ACCESS_CHANGED = "PROJECT_ACCESS_CHANGED",

  DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED",
  DOCUMENT_UPDATED = "DOCUMENT_UPDATED",
  DOCUMENT_DELETED = "DOCUMENT_DELETED",
  DOCUMENT_SHARED = "DOCUMENT_SHARED",
  DOCUMENT_ACCESS_CHANGED = "DOCUMENT_ACCESS_CHANGED",
  DOCUMENT_VERSION_CREATED = "DOCUMENT_VERSION_CREATED",
  DOCUMENT_SIGNED = "DOCUMENT_SIGNED",
  DOCUMENT_COMMENTED = "DOCUMENT_COMMENTED",

  USER_LOGGED_IN = "USER_LOGGED_IN",
  USER_LOGGED_OUT = "USER_LOGGED_OUT",
  USER_REGISTERED = "USER_REGISTERED",
  USER_UPDATED = "USER_UPDATED",
  USER_DEACTIVATED = "USER_DEACTIVATED",
  USER_ROLE_CHANGED = "USER_ROLE_CHANGED",

  SURVEY_CREATED = "SURVEY_CREATED",
  SURVEY_UPDATED = "SURVEY_UPDATED",
  SURVEY_DELETED = "SURVEY_DELETED",
  SURVEY_ACTIVATED = "SURVEY_ACTIVATED",
  SURVEY_CLOSED = "SURVEY_CLOSED",
  SURVEY_VOTED = "SURVEY_VOTED",
  SURVEY_RESULTS_VIEWED = "SURVEY_RESULTS_VIEWED",

  COMMENT_CREATED = "COMMENT_CREATED",
  COMMENT_UPDATED = "COMMENT_UPDATED",
  COMMENT_DELETED = "COMMENT_DELETED",
  COMMENT_LIKED = "COMMENT_LIKED",
  COMMENT_DISLIKED = "COMMENT_DISLIKED",

  CHAT_MESSAGE_SENT = "CHAT_MESSAGE_SENT",
  CHAT_MESSAGE_EDITED = "CHAT_MESSAGE_EDITED",
  CHAT_MESSAGE_DELETED = "CHAT_MESSAGE_DELETED",
  CHAT_ROOM_CREATED = "CHAT_ROOM_CREATED",
  CHAT_ROOM_JOINED = "CHAT_ROOM_JOINED",
  CHAT_ROOM_LEFT = "CHAT_ROOM_LEFT",

  NOTIFICATION_SENT = "NOTIFICATION_SENT",
  NOTIFICATION_READ = "NOTIFICATION_READ",
  NOTIFICATION_DELETED = "NOTIFICATION_DELETED",

  SYSTEM_BACKUP = "SYSTEM_BACKUP",
  SYSTEM_MAINTENANCE = "SYSTEM_MAINTENANCE",
  SYSTEM_ERROR = "SYSTEM_ERROR",
  SYSTEM_WARNING = "SYSTEM_WARNING",
}

export enum ActivityFilterType {
  ALL = "ALL",
  TASK = "TASK",
  PROJECT = "PROJECT",
  DOCUMENT = "DOCUMENT",
  USER = "USER",
  SURVEY = "SURVEY",
  COMMENT = "COMMENT",
  CHAT = "CHAT",
  NOTIFICATION = "NOTIFICATION",
  SYSTEM = "SYSTEM",
}

export enum ActivityExportFormat {
  PDF = "PDF",
  CSV = "CSV",
  JSON = "JSON",
}
