export enum DocumentTag {
    CC = 'CC',
    CTC = 'CTC',
    CTF = 'CTF',
    OC = 'OC',
    PVR = 'PVR',
    DV = 'DV',
    FA = 'FA',
    DJ = 'DJ',
    DC = 'DC',
    NI = 'NI',
    BDG = 'BDG',
    RAP = 'RAP',
    PLN = 'PLN',
    CRR = 'CRR',
    SPF = 'SPF',
    SPT = 'SPT',
    ETU = 'ETU',
    CHP = 'CHP',
    AVC = 'AVC',
    MNT = 'MNT',
    RCX = 'RCX'
  }
  
  export const DOCUMENT_TAG_LABELS: Record<DocumentTag, string> = {
    [DocumentTag.CC]: 'Cahier des Charges',
    [DocumentTag.CTC]: 'Contrat Client',
    [DocumentTag.CTF]: 'Contrat Fournisseur',
    [DocumentTag.OC]: 'Offre Commerciale',
    [DocumentTag.PVR]: 'Procès-Verbal de Réunion',
    [DocumentTag.DV]: 'Devis',
    [DocumentTag.FA]: 'Facture',
    [DocumentTag.DJ]: 'Document Juridique',
    [DocumentTag.DC]: 'Document Confidentiel',
    [DocumentTag.NI]: 'Note Interne',
    [DocumentTag.BDG]: 'Budget',
    [DocumentTag.RAP]: 'Rapport d\'Avancement',
    [DocumentTag.PLN]: 'Plan de Projet',
    [DocumentTag.CRR]: 'Compte Rendu',
    [DocumentTag.SPF]: 'Spécifications Fonctionnelles',
    [DocumentTag.SPT]: 'Spécifications Techniques',
    [DocumentTag.ETU]: 'Étude de Faisabilité',
    [DocumentTag.CHP]: 'Charte de Projet',
    [DocumentTag.AVC]: 'Avenant de Contrat',
    [DocumentTag.MNT]: 'Manuel Technique',
    [DocumentTag.RCX]: 'Rapport de Recette'
  };